{% set version = "3.2.2" %}

package:
  name: graphene
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/g/graphene/graphene-{{ version }}.tar.gz
  sha256: 5b03e72770dc901f40be55784058d6bb1d952a49eb819a4a085962d5e1cf5fcf

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - graphql-core >=3.1,<3.3
    - graphql-relay >=3.1,<3.3
    - aniso8601 >=8,<10

test:
  source_files:
    - graphene/tests
  files:
    - fix_tests.py
  requires:
    # for pip check
    - pip
    # for tests
    - iso8601 >=1,<2
    - mock >=4,<5
    - pytest >=6,<7
    - pytest-asyncio >=0.16,<2
    - pytest-benchmark >=3.4,<4
    - pytest-cov >=3,<4
    - pytest-mock >=3,<4
    - pytz ==2022.1
    - snapshottest >=0.6,<1
  imports:
    - graphene
  commands:
    - pip check
    - python fix_tests.py
    - cd graphene/tests && pytest -vv --cov graphene --cov-report term-missing:skip-covered --no-cov-on-fail --cov-fail-under=48

about:
  home: https://graphene-python.org
  license_file: LICENSE
  license: MIT
  license_family: MIT
  summary: GraphQL Framework for Python
  dev_url: https://github.com/graphql-python/graphene
  doc_url: https://docs.graphene-python.org

extra:
  recipe-maintainers:
    - bollwyvl
    - carlodri
