{% set version = "3.4.1" %}

package:
  name: graphene
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/g/graphene/graphene-{{ version }}.tar.gz
  sha256: 828a8d7b1bce450566a72cc8733716c20f3acfc659960de73dd38f46dc302040

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools
  run:
    - graphql-core >=3.1,<3.3
    - graphql-relay >=3.1,<3.3
    - python-dateutil>=2.7.0,<3
    - python >=3.6
    - typing_extensions >=4.7.1,<5

test:
  source_files:
    - graphene/tests
  files:
    - fix_tests.py
  requires:
    # for pip check
    - pip
    # for tests
    - pytest >=8,<9
    - pytest-asyncio >=0.16,<2
    - pytest-benchmark >=4,<5
    - pytest-cov >=5,<6
    - pytest-mock >=3,<4
  imports:
    - graphene
  commands:
    - pip check
    - python fix_tests.py
    - cd graphene/tests
    - coverage run --source=graphene --branch -m pytest -vv --tb=long --color=yes
    - coverage report --show-missing --skip-covered --fail-under=48

about:
  home: https://graphene-python.org
  license_file: LICENSE
  license: MIT
  license_family: MIT
  summary: GraphQL Framework for Python
  dev_url: https://github.com/graphql-python/graphene
  doc_url: https://docs.graphene-python.org

extra:
  recipe-maintainers:
    - bollwyvl
    - carlodri
