{% set name = "graphene" %}
{% set version = "2.1.2" %}
{% set bundle = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash = "98e74c32d0415e5b5362738c1c1cb4b7a4e411b5d3d828abb29ccd3efb378c44" %}
{% set build = 0 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  {{ hash_type }}: {{ hash }}

build:
  noarch: python
  number: {{ build }}
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - six >=1.10.0
    - graphql-core >=1.1
    - graphql-relay >=0.4.5
    - promise >=2.0

test:
  imports:
    - graphene
    - graphene.pyutils
    - graphene.relay
    - graphene.test
    - graphene.types
    - graphene.utils

about:
  home: http://graphene-python.org/
  license_file: {{ RECIPE_DIR }}/LICENSE
  license: MIT
  license_family: MIT
  summary: 'GraphQL Framework for Python'
  dev_url: https://github.com/graphql-python/graphene
  doc_url: http://docs.graphene-python.org/en/latest/

extra:
  recipe-maintainers:
    - pmlandwehr
